---
# github.com/hashicorp/vagrant

- apt:
    name: vagrant
  remote_user: root
  when: ansible_os_family == 'Debian' and vagrant.source == 'debian'

- get_url:
    url: 'https://releases.hashicorp.com/vagrant/{{ vagrant.version }}/vagrant_{{ vagrant.version }}_x86_64.deb'
    dest: '/var/tmp/vagrant_{{ vagrant.version }}.deb'
    mode: 0644
  remote_user: root
  when: ansible_os_family == 'Debian' and vagrant.source == 'upstream'

- apt:
    deb: '/var/tmp/vagrant_{{ vagrant.version }}.deb'
  notify:
  - reinstall vagrant plugins
  remote_user: root
  when: ansible_os_family == 'Debian' and vagrant.source == 'upstream'

- homebrew_cask:
    name: vagrant
  when: ansible_system == 'Darwin'

- template:
    src: sudo.txt
    dest: /etc/sudoers.d/vagrant
    mode: 0440
  remote_user: root
  when: ansible_system == 'Darwin'

- git:
    repo: git@github.com:hashicorp/vagrant.git
    dest: '{{ ansible_user_dir }}/src/vagrant'
    version: 'v{{ vagrant.version }}'
  when: vagrant.source == 'github'

# bundle accidentally ran in ~/src/vagrant on w1, before GEM_HOME was defined, which installed gems globally.
# These were the clean up steps:
#sudo find /usr/local/bin -mindepth 1 -mtime -1 -delete
#sudo find /var/lib/gems/2.5.0 -mindepth 2 -mtime -1 -delete
- bundler:
    state: present
    chdir: '{{ ansible_user_dir }}/src/vagrant'
  environment:
    GEM_HOME: '{{ ansible_user_dir }}/.gem'
  when: vagrant.source == 'github'

- command: bundle --binstubs exec
  args:
    chdir: '{{ ansible_user_dir }}/src/vagrant'
    creates: '{{ ansible_user_dir }}/src/vagrant/exec/vagrant'
  environment:
    GEM_HOME: '{{ ansible_user_dir }}/.gem'
  when: vagrant.source == 'github'

- file:
    dest: /usr/local/bin/vagrant
    src: '{{ ansible_user_dir }}/src/vagrant/exec/vagrant'
    state: link
  remote_user: root
  when: vagrant.source == 'github'
