---
# github.com/hashicorp/vagrant

# TODO: Vagrant in Stretch is not compatible with VirtualBox 5.2. Wait for newer Vagrant version.
#- apt:
#    name: vagrant
#  remote_user: root
#  when: ansible_os_family == 'Debian'

- get_url:
    url: 'https://releases.hashicorp.com/vagrant/{{ vagrant.version }}/vagrant_{{ vagrant.version }}_x86_64.deb'
    dest: '/var/tmp/vagrant_{{ vagrant.version }}.deb'
  remote_user: root
  when: ansible_os_family == 'Debian'

- apt:
    deb: '/var/tmp/vagrant_{{ vagrant.version }}.deb'
  notify:
  - reinstall vagrant plugins
  remote_user: root
  when: ansible_os_family == 'Debian'

- homebrew_cask:
    name: vagrant
  when: ansible_system == 'Darwin'
