---
# https://github.com/hashicorp/vagrant

# Vagrant in Stretch is not compatible with VirtualBox 5.2.
#- apt:
#    name: vagrant
#  become: true
#  when: ansible_os_family == 'Debian'

- file:
    path: '{{ ansible_user_dir }}/tmp'
    state: directory
  when: ansible_os_family == 'Debian'

- get_url:
    url: 'https://releases.hashicorp.com/vagrant/{{ vagrant_version }}/vagrant_{{ vagrant_version }}_x86_64.deb'
    dest: '{{ ansible_user_dir }}/tmp/vagrant_{{ vagrant_version }}.deb'
  when: ansible_os_family == 'Debian'

- apt:
    deb: '{{ ansible_user_dir }}/tmp/vagrant_{{ vagrant_version }}.deb'
  become: true
  when: ansible_os_family == 'Debian'

- homebrew_cask:
    name: vagrant
  when: ansible_system == 'Darwin'
